### ISSUE TITLE
Return value is not compatible with required type

### ISSUE THREAD

**Issue by ScDor** [optapy/optapy#18]
Hi, 
I am getting the `Return value is not compatible with required type` error - how can I tell the types involved (expected and actual), so I can solve this error?

By the way, is the `NotADirectoryError` and `PermissionError` errors following the `TypeError` in the end 'real', or are theycaused by the type mismatch? 

Thanks

```
C:\Users\User\Project\venv\Scripts\python.exe C:/Users/User/Project/optapy1.py
11:11:20,084 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:11:20,084 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:11:20,084 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/Users/User/AppData/Local/Temp/tmpy3fynomc/optapy-8.11.0.Final-sources.jar!/logback.xml]
11:11:20,084 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
11:11:20,084 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Users/User/AppData/Local/Temp/tmpy3fynomc/optapy-8.11.0.Final-sources.jar!/logback.xml]
11:11:20,084 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Users/User/AppData/Local/Temp/tmpy3fynomc/optapy-8.11.0.Final.jar!/logback.xml]
11:11:20,091 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@4f0f2942 - URL [jar:file:/C:/Users/User/AppData/Local/Temp/tmpy3fynomc/optapy-8.11.0.Final-sources.jar!/logback.xml] is not of type file
11:11:20,152 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:11:20,152 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:11:20,156 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [consoleAppender]
11:11:20,159 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:11:20,204 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.optaplanner] to INFO
11:11:20,204 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
11:11:20,204 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [consoleAppender] to Logger[ROOT]
11:11:20,205 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:11:20,207 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2657d4dd - Registering current configuration as safe fallback point

Traceback (most recent call last):
  File "C:\Users\User\Project\optapy1.py", line 129, in <module>
    solution = solve(solverConfig, generateProblem())
  File "C:\Users\User\Project\venv\lib\site-packages\optapy\optaplanner_java_interop.py", line 299, in solve
    solution = _unwrap_java_object(PythonSolver.solve(solver_config,
TypeError: Return value is not compatible with required type.

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpy3fynomc\\antlr-runtime-3.5.2.jar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tempfile.py", line 801, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpy3fynomc\\antlr-runtime-3.5.2.jar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\weakref.py", line 656, in _exitfunc
    f()
  File "C:\Program Files\Python39\lib\weakref.py", line 580, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Program Files\Python39\lib\tempfile.py", line 816, in _cleanup
    cls._rmtree(name)
  File "C:\Program Files\Python39\lib\tempfile.py", line 812, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Program Files\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python39\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Python39\lib\tempfile.py", line 804, in onerror
    cls._rmtree(path)
  File "C:\Program Files\Python39\lib\tempfile.py", line 812, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Program Files\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python39\lib\shutil.py", line 599, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Program Files\Python39\lib\shutil.py", line 596, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpy3fynomc\\antlr-runtime-3.5.2.jar'

Process finished with exit code 1
```

**Comment by Christopher-Chianelli** [comment]
The `NotADirectory` and `PermissionError` seems to be an issue with temporary directories in Windows that occur on program end (I got the  `NotADirectory` and `PermissionError` after solving, so my guess is something happens when removing the temporary directory; probably caused by Java not being closed before the directory is removed).

There are two possible issues:
1. Missing decorator on Planning Solution / Planning Entity / Problem Fact
2. Not passing a `optapy.types.SolverConfig` as a second argument.

My guess is it 1.; do you have `@planning_solution` on your planning solution class definition (like https://github.com/optapy/optapy/blob/bfedb6e863973f9b182438db6e359d366bb0f99c/optapy-quickstarts/school-timetabling/domain.py#L81-L113)

Otherwise, you didn't pass a SolverConfig as the first argument;

See:
https://github.com/optapy/optapy/blob/bfedb6e863973f9b182438db6e359d366bb0f99c/optapy-quickstarts/school-timetabling/main.py#L70-L75

I can improve the error message; I'll see if I can do anything about the OS errors on Windows (doesn't happen on Linux).

**Comment by Christopher-Chianelli** [comment]
The `NotADirectory` and `PermissionError` should be fixed by https://github.com/optapy/optapy/pull/19 ; meaningful type errors will be for another PR.

**Comment by hebbsThakral** [comment]
I get the same error. Not sure if it's related, but when I changed a string to an datetime.date() the Joiner threw this error:

changed:
`timeslot_list.append(Timeslot(id, "THURSDAY", time(hour=10, minute=0), time(hour=10, minute=20)) )`
to
`timeslot_list.append(Timeslot(id, date(2021,12,2"), time(hour=10, minute=0), time(hour=10, minute=20)) )`

then the joiner using this field (match.timeslot.match_date) throws the error. If I comment the joiner out or revert to a string it works fine:

`def sections_play_rounds_at_similar_time(constraint_factory):
    # sections should play their rounds at the same time across multiple pitches
    return constraint_factory \
        .from_(MatchClass) \
        .join(MatchClass,
              [
                  Joiners.equal(lambda match: match.section),
                  Joiners.equal(lambda match: match.match_type),
                  Joiners.equal(lambda match: match.round),
                  #Joiners.equal(lambda match: match.timeslot.match_date),
                  Joiners.lessThan(lambda match: match.id)
              ]) \
        .filter(within_20_minutes) \
        .reward("Sections play rounds at a similar time", HardSoftScore.ofSoft(5))`

**Comment by hebbsThakral** [comment]
I also tried datetime(2021,12,2) instead of date(2021,12,2) and still get "TypeError: Return value is not compatible with required type."

**Comment by Christopher-Chianelli** [comment]
Can confirm it due to datetime.date / datetime.datetime not being a Java compatible type. I'll try improving the error message:

```
TypeError: At least one constraint have a function that did not return a Java compatible return type (for example, datetime.date). In general: filtering functions must return either True or False; functions passed to Joiners must return a number, bool, str, list, dict,or a class decorated with @problem_fact or @planning_entity; functions passed to rewardBy/penalizeBy must return an int. Maybe convert the value returned by the Joiner function to str (ex: Joiners.equal(lambda entity: str(entity.date))?
```

I don't seem to have access to which function/constraint caused the TypeError, so I can only give general advice.

**Comment by Christopher-Chianelli** [comment]
Done; New OptaPy version released: 8.14.0a0

New Features:

- All Python Types are supported in Joiners/ConstraintCollectors/etc, so that TypeError now never happens. If you happen to return a bad type in a method that expects a particular type (ex: returning a str instead of a bool in a filter), a TypeError will be raised with some general helping info
- The following API from OptaPlanner have been exposed: `SolverFactory`, `SolverManager`, `ScoreManager` (which can be accessed via `solver_factory_create`, `solver_manager_create`, `score_manager_create`).
- The following annotations from OptaPlanner been exposed as annotations: `@anchor_shadow_variable`, `@inverse_relation_shadow_variable`, `@planning_pin`; pinning_filter is also now available as an optional value that can be defined on `@planning_entity`
- SolverFactory is for blocking solving, SolverManager is for asynchronously solving, ScoreManager is to get the score and violated constraints without solving.
- Type stubs have been added via `stubgenj`

Deprecations:

- `from` have been deprecated in OptaPlanner (`from_` in OptaPy) due to its semantics changing depending on if over-constrained planning is used. Now use `forEach`/`forEachIncludingNullVars` instead, which has consistent semantics in both regular and over-constrained planning.

Breaking Changes:

- `solve` as a global function has been removed from OptaPy as there is no equivalent static method in OptaPlanner yet. Replace `solve(solver_config, problem)` with `solver_factory_create(solver_config).buildSolver().solve(problem)`.
